name: webdev_proxy
description: Proxies HTTP requests to "webdev serve" to support debugging client-side Dart scripts with Dart HTTP servers.
version: 1.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.13.5
  logging: ^1.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.0.0
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
