name: webdev_proxy
description: Proxies HTTP requests to "webdev serve" to support debugging client-side Dart scripts with Dart HTTP servers.
version: 2.0.0-alpha

environment:
  sdk: '^3.0.0'

dependencies:
  http: ^1.1.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
  test: ^1.24.9
