name: webdev_proxy
description: Proxies HTTP requests to "webdev serve" to support debugging client-side Dart scripts with Dart HTTP servers.
version: 1.0.0
author: Hoylen Sue <hoylen@hoylen.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  logging: "^0.11.3"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ">=1.3.0 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"

